require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe FundingSourcesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # FundingSource. As you add validations to FundingSource, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FundingSourcesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all funding_sources as @funding_sources" do
      funding_source = FundingSource.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:funding_sources)).to eq([funding_source])
    end
  end

  describe "GET #show" do
    it "assigns the requested funding_source as @funding_source" do
      funding_source = FundingSource.create! valid_attributes
      get :show, {:id => funding_source.to_param}, valid_session
      expect(assigns(:funding_source)).to eq(funding_source)
    end
  end

  describe "GET #new" do
    it "assigns a new funding_source as @funding_source" do
      get :new, {}, valid_session
      expect(assigns(:funding_source)).to be_a_new(FundingSource)
    end
  end

  describe "GET #edit" do
    it "assigns the requested funding_source as @funding_source" do
      funding_source = FundingSource.create! valid_attributes
      get :edit, {:id => funding_source.to_param}, valid_session
      expect(assigns(:funding_source)).to eq(funding_source)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new FundingSource" do
        expect {
          post :create, {:funding_source => valid_attributes}, valid_session
        }.to change(FundingSource, :count).by(1)
      end

      it "assigns a newly created funding_source as @funding_source" do
        post :create, {:funding_source => valid_attributes}, valid_session
        expect(assigns(:funding_source)).to be_a(FundingSource)
        expect(assigns(:funding_source)).to be_persisted
      end

      it "redirects to the created funding_source" do
        post :create, {:funding_source => valid_attributes}, valid_session
        expect(response).to redirect_to(FundingSource.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved funding_source as @funding_source" do
        post :create, {:funding_source => invalid_attributes}, valid_session
        expect(assigns(:funding_source)).to be_a_new(FundingSource)
      end

      it "re-renders the 'new' template" do
        post :create, {:funding_source => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested funding_source" do
        funding_source = FundingSource.create! valid_attributes
        put :update, {:id => funding_source.to_param, :funding_source => new_attributes}, valid_session
        funding_source.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested funding_source as @funding_source" do
        funding_source = FundingSource.create! valid_attributes
        put :update, {:id => funding_source.to_param, :funding_source => valid_attributes}, valid_session
        expect(assigns(:funding_source)).to eq(funding_source)
      end

      it "redirects to the funding_source" do
        funding_source = FundingSource.create! valid_attributes
        put :update, {:id => funding_source.to_param, :funding_source => valid_attributes}, valid_session
        expect(response).to redirect_to(funding_source)
      end
    end

    context "with invalid params" do
      it "assigns the funding_source as @funding_source" do
        funding_source = FundingSource.create! valid_attributes
        put :update, {:id => funding_source.to_param, :funding_source => invalid_attributes}, valid_session
        expect(assigns(:funding_source)).to eq(funding_source)
      end

      it "re-renders the 'edit' template" do
        funding_source = FundingSource.create! valid_attributes
        put :update, {:id => funding_source.to_param, :funding_source => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested funding_source" do
      funding_source = FundingSource.create! valid_attributes
      expect {
        delete :destroy, {:id => funding_source.to_param}, valid_session
      }.to change(FundingSource, :count).by(-1)
    end

    it "redirects to the funding_sources list" do
      funding_source = FundingSource.create! valid_attributes
      delete :destroy, {:id => funding_source.to_param}, valid_session
      expect(response).to redirect_to(funding_sources_url)
    end
  end

end
